### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by WopsS** [yamashi/SkyrimOnline#63]
@yamashi I remember you told to add **MyGUIEngine.pdb**, am I right?

**Comment by WopsS** [comment]
Oh, @yamashi please check my last response. 
https://github.com/WopsS/SkyrimOnline/commit/2d627e191411450bd48d3b29b1b8343d590be8bc#commitcomment-10063341

**Comment by yamashi** [comment]
Doubt we would need MyGUIEngine.pdb...

**Comment by WopsS** [comment]
I remember you told me to add something for debug, but I can't remember what.

**Comment by yamashi** [comment]
Maybe I wanted the debug version of the MyGUI lib, not sure.

**Comment by Paul-Moura** [comment]
Hi Yamashi,
I've been chatting with Megaman through the messaging system on http://skyrim.ophelia-core.com and he referred me to contact you by leaving a post here. I'm a C# developer but have been studying C++. I've looked over most of the code for this mod but I have a few questions. If you have sometime, I'd love to talk about this project so that I could begin assisting in continuing its development.
