### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by testman42** [yamashi/SkyrimOnline#68]
Is it dead?
Did dream of proper Skyrim multiplayer die with it?

**Comment by ChairGraveyard** [comment]
Lurker - I don't think SkyrimOnline is dead, necessarily, so much as development is slow.

That said, I'd encourage you to check out Tamriel Online (recently released this past week) on the Nexus, as it has pretty functional (smaller-scale) multiplayer already working :)

**Comment by TheMeGaMaN** [comment]
Yamashi has been busy with his job. He'll let us all know if he finds time to develop.

The other people interested in working on the mod have gone off the radar or are in a hold for reason or another. You'll find it that there are no commits, because developers lacking the time to go forward.

Tamriel Online is something you should download if you seek basic multiplayer, but it's nothing mindblowing or something that haven't been implemented in Skyrim Online back in 2011.
Check it out, but i wouldn't recommend it for more than testing.

**Comment by WopsS** [comment]
@TheMeGaMaN you're wrong. I'm still here, I still watch this repository and the forum, but because Yamashi doesn't spoken with me in last months I didn't do anything.

**Comment by yamashi** [comment]
I remember telling you that we need a python script to generate packet structures, other than that I will try to crack open how to sync events this week, if I succeed we will be done with research and be able to start implementing full world sync.

**Comment by WopsS** [comment]
@yamashi  you're correct, but @hibbydibby told us he will do it.

**Comment by yamashi** [comment]
Let's talk about it tomorrow on steam.

**Comment by WopsS** [comment]
Ok.
